compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  timeout: 1800
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
  zero_optimization:
    stage: 3
    stage3_gather_16bit_weights_on_model_save: false # 禁用保存时全量参数聚合
    offload_optimizer:
      device: cpu # 强制优化器卸载到CPU
    offload_param: 
      device: cpu # 强制参数卸载到CPU

  activation_checkpointing: true # 确保激活检查点启用

distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
